project_id = "cikslrwypenntopysaej"

[functions.send-po-email]
verify_jwt = false

[functions.xero-auth-url]
verify_jwt = false

[functions.xero-oauth-callback]
verify_jwt = false

[functions.xero-sync-invoice]
verify_jwt = false

[functions.xero-sync-production-journal]
verify_jwt = false

[functions.xero-get-accounts]
verify_jwt = false
