project_id = "cikslrwypenntopysaej"

[functions.send-po-email]
verify_jwt = false

[functions.xero-auth-url]
verify_jwt = false

[functions.xero-oauth-callback]
verify_jwt = false

[functions.xero-sync-invoice]
verify_jwt = false

[functions.xero-sync-production-journal]
verify_jwt = false

[functions.xero-get-accounts]
verify_jwt = false

[functions.xero-sync-po-bill]
verify_jwt = false

[functions.xero-sync-fg-completion]
verify_jwt = false

[functions.usda-food-search]
verify_jwt = false

[functions.extract-nutrition-pdf]
verify_jwt = false

[functions.create-employee-user]
verify_jwt = false

[functions.send-employee-welcome-email]
verify_jwt = false

[functions.test-email]
verify_jwt = false
